### PR TITLE
add missing django-compressor requirement

### PR DESCRIPTION
**Pull request by VladSB**

### CODE REVIEW

**Comment by palazzem** [comment]
Hi, thank you for your PR! anyway, I'm not maintaining this repository anymore, so maybe a contributor with write permission can double check if this solves the issue (and it surely does), and if there are other issues like this one.

@jab3z can you take a look and see if this issue occurs even on your projects?

Thank you!

**Comment by palazzem** [comment]
Thank you @jab3z for the double check! And thank you @VladSB for the PR! :)

**Comment by jab3z** [comment]
You welcome.
PS: @VladSB is my colleague :)

**Comment by palazzem** [comment]
Eheh, didn't know that! Let me know if there are any issues or improvement to take care of :+1:

**Comment by jab3z** [comment]
Yes, I will need to update the documentation and I'm thinking to add djangocms cascade in the requirements.

**Comment by VladSB** [comment]
You're welcome and thanks for the help this project offers :D

**Pull request merged**
